version: '3'
services:

  citd_api:
    build:
      context: ./codeinthedark_server
      dockerfile: dev.Dockerfile
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    networks:
      - citd
    volumes:
      - ./codeinthedark_server/src:/usr/src/app/src
    depends_on:
      - citd_mongo

  citd_rating:
    build:
      context: ./codeinthedark_rating
      dockerfile: dev.Dockerfile
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - citd
    volumes:
      - ./codeinthedark_rating/src:/usr/local/citd-rating/src

  citd_viewer:
    build:
      context: ./codeinthedark_viewer
      dockerfile: dev.Dockerfile
    restart: always
    user: "${UID}:${GID}"
    networks:
      - citd
    ports:
      - "4200:4200"
    volumes:
      - ./codeinthedark_viewer/src:/usr/src/app/src

  citd_editor:
    build:
      context: ./editor
      dockerfile: dev.Dockerfile
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "9000:9000"
    networks:
      - citd
    volumes:
      - ./editor/app:/usr/src/app/app

  citd_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - citd
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/etc/mongo

  citd_vhost:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    networks:
      - citd
    ports:
      # Public HTTP Port:
      - 80:80
      # Public HTTPS Port:
      - 443:443
      # Admin Web Port:
      - 81:81
    volumes:
      # Make sure this config.json file exists as per instructions above:
      - ./nginx/config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - citd_vhostdb

  citd_vhostdb:
    image: mariadb
    restart: always
    networks:
      - citd
    environment:
      MYSQL_ROOT_PASSWORD: ${VHOSTDB_ROOT_PASSWORD}
      MYSQL_DATABASE: "npm"
      MYSQL_USER: ${VHOSTDB_USER}
      MYSQL_PASSWORD: ${VHOSTDB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql


volumes:
  mongo_data:

networks:
  citd:
